service: python2

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  timeout: 30

functions:
  getip2:
    handler: handler.getIp2

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux