service: python

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  timeout: 30

functions:
  getip:
    handler: handler.getIp

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - a/** # virtualenv
    - venv/** # virtualenv